### ISSUE TITLE
Top-right corner not filled.

### ISSUE THREAD

**Issue by perladoubinsky** [karazijal/clevrtex-generation#4]
Hello and thanks for the repo. When changing the size of images from 320x240 to 128x128 or 256x256 in local_test.bash (I didn't make any other modifications to the code) some images appear with the top-right corner not filled (cf. attached example). I don't see this problem with images of size 320x240.
Do you have any idea what might be causing this ? 
Thank you.
![LOCAL_debug_000003](https://user-images.githubusercontent.com/22800942/155845577-d7f1e3a0-b6b6-4bbc-8663-0bf422d767a1.png)

**Comment by karazijal** [comment]
By changing the aspect ration, extra image space in top and bottom is revealed. The unfilled area is simple the edge of the photo backdrop and black void behind it (nothing else exists in the scene). If you want to render at a different aspect ratio, I would recommend moving the camera closer/zooming in. It can be done by modifying the basic scene file. 

Alternatively, you could render at the same aspect ration (4:3) and just cut off left and right sides from images after the rendering is done. That is similar to what happens with ClevrTex and CLEVR benchmarks during data loading.

For purple objects, see [Issue 3](https://github.com/karazijal/clevrtex-generation/issues/3).

**Comment by perladoubinsky** [comment]
Thank you!
